# Generated by Django 5.0.1 on 2024-02-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('branch_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('scheme_evaluation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_sem', models.IntegerField()),
                ('stu_usn', models.CharField(max_length=20, unique=True)),
                ('sec', models.CharField(max_length=2)),
                ('roll_no', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam_app.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100, unique=True)),
                ('sub_code', models.CharField(max_length=20)),
                ('sub_credit', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam_app.branch')),
                ('sub_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam_app.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam_app.branch')),
                ('sub_handling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='IA_marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ia_1_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ia_2_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ia_3_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quiz', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assignment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam_app.student')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam_app.subject')),
            ],
        ),
    ]
