# Generated by Django 5.0 on 2024-02-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam_app', '0002_remove_ia_marks_ia_1_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ia_marks',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='ia_marks',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='ia_marks',
            name='total_marks',
        ),
    ]
