# Generated by Django 5.0 on 2024-03-01 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_app', '0003_remove_ia_marks_assignment_remove_ia_marks_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ia_marks',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iam_app.batch'),
        ),
        migrations.AddField(
            model_name='ia_marks',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='iam_app.branch'),
        ),
        migrations.AddField(
            model_name='ia_marks',
            name='sec',
            field=models.CharField(default='Z', max_length=2),
        ),
        migrations.AddField(
            model_name='ia_marks',
            name='stu_sem',
            field=models.IntegerField(default=0),
        ),
    ]
